```yaml
name: Appknox

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  security-events: write

jobs:
  appknox:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Find APK
        run: |
          echo "Searching for APK files..."
          find . -type f -name "*.apk" -print

      - name: Appknox GitHub action
        uses: appknox/appknox-github-action@b7d2bfb2321d5544e97bffcba48557234ab953a4
        with:
          appknox_access_token: ${{ secrets.APPKNOX_ACCESS_TOKEN }}
          file_path: app-debug.apk
          risk_threshold: MEDIUM
          sarif: Enable

      - name: Check SARIF file
        if: always()
        run: |
          if [ -f report.sarif ]; then
            echo "SARIF file found."
          else
            echo "SARIF file not found. Skipping upload."
          fi

      - name: Upload SARIF to GHAS
        if: always() && hashFiles('report.sarif') != ''
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: report.sarif
```
